/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/LogoModel.glb -o ./src/components/LogoModel.jsx 
*/

import React, { useState } from "react";
import { useGLTF, MeshTransmissionMaterial, Sphere } from "@react-three/drei";
import * as THREE from "three";
import { useThree } from "@react-three/fiber";

export function LogoModel(props) {
  const { nodes, materials } = useGLTF("/LogoModel.glb");
  const [wireframeOn,setWireframeOn] = useState(false)
  const [wireframeColor, setWireframeColor] = useState('black');
  const { viewport } = useThree()

  const sphereGeometry1 = new THREE.SphereGeometry(1, 8, 8); // Lower detail sphere
  const sphereGeometry2 = new THREE.SphereGeometry(1, 8, 8); // Lower detail sphere
  const sphereGeometry3 = new THREE.SphereGeometry(1, 8, 8); // Lower detail sphere

  return (
    <group rotation={[-0.014, -1.55, 0]} scale={viewport.width/140} {...props} dispose={null}>
      {/* <mesh
        geometry={sphereGeometry1}
        position={[9.219, 5.32, -6.223]}
        scale={5}
      >
        <meshStandardMaterial wireframe={wireframeOn} color={wireframeColor}/>
      </mesh> */}
      <mesh
        geometry={sphereGeometry2}
        position={[-1.798, 5.32, -6.223]}
        scale={5}
      >
        <meshStandardMaterial wireframe={wireframeOn} color={wireframeColor}/>
      </mesh>
      {/* <mesh
        geometry={sphereGeometry3}
        position={[-11.226, 5.32, -6.223]}
        scale={3}
      >
        <meshStandardMaterial wireframe={wireframeOn} color={wireframeColor}/>
      </mesh> */}
      <mesh
        geometry={nodes.큐브.geometry}
        position={[0.931, -2.215, 12.345]}
        rotation={[0, 0, Math.PI / 4]}
        scale={[1.134, 1.134, 1]}
      >
        <meshStandardMaterial wireframe={wireframeOn} color={wireframeColor}/>
      </mesh>
      <mesh
        geometry={nodes.큐브001.geometry}
        position={[0.37, -13.349, -3.186]}
        rotation={[Math.PI / 2, 0, Math.PI / 4]}
        scale={[1.056, 1.056, 1]}
      >
        <meshStandardMaterial wireframe={wireframeOn} color={wireframeColor}/>
      </mesh>
      <mesh
        geometry={nodes.큐브002.geometry}
        position={[9.219, -4.416, 2.559]}
        rotation={[Math.PI / 4, 0, 0]}
        scale={[1, 1.197, 1]}
      >
        <meshStandardMaterial wireframe={wireframeOn} color={wireframeColor}/>
      </mesh>
    </group>
  );
}

useGLTF.preload("/LogoModel.glb");
