/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/LogoModel.glb -o ./src/components/LogoModel.jsx 
*/

import React from "react";
import { useGLTF, MeshTransmissionMaterial } from "@react-three/drei";
import * as THREE from "three";

export function LogoModel(props) {
  const { nodes, materials } = useGLTF("/LogoModel.glb");
  return (
    <group rotation={[-0.014, -1.55, 0]} scale={0.3} {...props} dispose={null}>
      <mesh
        geometry={nodes.구체.geometry}
        position={[9.219, 5.32, -6.223]}
        scale={5}
      >
        <meshNormalMaterial/>
      </mesh>
      <mesh
        geometry={nodes.구체001.geometry}
        position={[-1.798, 5.32, -6.223]}
        scale={4}
      >
        <meshNormalMaterial/>
      </mesh>
      <mesh
        geometry={nodes.구체002.geometry}
        position={[-11.226, 5.32, -6.223]}
        scale={3}
      >
        <meshNormalMaterial/>
      </mesh>
      <mesh
        geometry={nodes.큐브.geometry}
        position={[0.931, -2.215, 12.345]}
        rotation={[0, 0, Math.PI / 4]}
        scale={[1.134, 1.134, 1]}
      >
        <meshNormalMaterial/>
      </mesh>
      <mesh
        geometry={nodes.큐브001.geometry}
        position={[0.37, -13.349, -3.186]}
        rotation={[Math.PI / 2, 0, Math.PI / 4]}
        scale={[1.056, 1.056, 1]}
      >
        <meshNormalMaterial/>
      </mesh>
      <mesh
        geometry={nodes.큐브002.geometry}
        position={[9.219, -4.416, 2.559]}
        rotation={[Math.PI / 4, 0, 0]}
        scale={[1, 1.197, 1]}
      >
        <meshNormalMaterial/>
      </mesh>
    </group>
  );
}

useGLTF.preload("/LogoModel.glb");
